version: '3'

services:
    pandoc:
        image: jagregory/pandoc
        volumes:
          - ./:/source
        command: -s --toc manual/MANUAL.md -o docs/index.html

    deb:
        build: ./src/packaging/deb
        volumes:
          - ./:/data
        command: sh /data/src/packaging/deb/build_deb.sh

    docs:
        image: asciidoctor/docker-asciidoctor

        volumes:
        - ./manual:/documents
        - ./docs:/html

        command: asciidoctor -o /html/index.html MANUAL.adoc



